[package]
name = "minecrevy-bytes"
version = "0.1.0"
edition = "2024"

[dependencies]
# workspace
embedded-byteorder = { workspace = true }
# external
heapless = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }