[package]
name = "minecrevy-encdec"
version = "0.1.0"
edition = "2024"

[dependencies]
# workspace
embedded-byteorder = { workspace = true }
minecrevy-bytes = { workspace = true }
# external
heapless = { workspace = true }